"""add title column to Goal model

Revision ID: 85147ce03a7a
Revises: cf6743f81d16
Create Date: 2025-05-07 01:34:24.691516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85147ce03a7a'
down_revision = 'cf6743f81d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
